export const URL = "http://localhost:2000/api"
export const URL_IMG = 'http://localhost:2000/'
export const GET_CAROUSEL = "GET_CAROUSEL"
export const GET_CATEGORY = "GET_CATEGORY"


// PRODUCT
export const GET_PRODUCT = "GET_PRODUCT"
export const GET_PRODUCT_START = "GET_PRODUCT_START"
export const GET_PRODUCT_END = "GET_PRODUCT_END"
export const GET_PRODUCT_ADMIN = "GET_PRODUCT_ADMIN"
export const GET_PRODUCT_COLOR = "GET_PRODUCT_COLOR"
export const GET_PRODUCT_DETAILS = "GET_PRODUCT_DETAILS"
export const GET_PRODUCT_CATEGORY = "GET_PRODUCT_CATEGORY"
export const GET_PRODUCT_WAREHOUSE = "GET_PRODUCT_WAREHOUSE"
export const ADD_PRODUCT = "ADD_PRODUCT"

// CART
export const GET_CART = "GET_CART"
export const GET_CART_START = "GET_CART_START"
export const GET_CART_END = "GET_CART_END"
export const CART_ERROR = "GET_CART_ERROR"
export const ERROR_ONGKIR = "ERROR_ONGKIR"
export const UPLOAD_PAYMENT_ERROR = "UPLOAD_PAYMENT_ERROR"

// WAREHOUSE
export const GET_WAREHOUSE = "GET_WAREHOUSE"
export const GET_WAREHOUSE_START = "GET_WAREHOUSE_START"
export const GET_WAREHOUSE_END = "GET_WAREHOUSE_END"
// USER
export const VERIFY = "VERIFY"
export const VERIFY_ERROR = "VERIFY_ERROR"
export const LOG_IN_START = "LOG_START"
export const LOG_IN = "LOG_IN"
export const LOG_IN_END = "LOG_OUT_END"
export const LOG_IN_ERROR = "LOG_IN_ERROR"
export const REGISTER_START = "REGISTER_START"  
export const REGISTER = "REGISTER"  
export const REGISTER_END = "REGISTER_END"  
export const REGISTER_ERROR = "REGISTER_ERROR"  
export const KEEP_LOGIN = "KEEP_LOGIN"
export const LOG_OUT = "LOG_OUT"

// PROFILE
export const GET_PROFILE = "GET_PROFILE"
export const GET_FAVORITE = "GET_FAVORITE"
export const EDIT_PROFILE = "EDIT_PROFILE"
export const UPLOAD_PIC_ERROR = "UPLOAD_PIC_ERROR"

// ORDER
export const GET_ORDER_ALL = "GET_ORDER_ALL"
export const GET_ORDER_USER = "GET_ORDER_USER"

// ADDRESS
export const GET_ADDRESS = "GET_ADDRESS"
export const ADD_ADDRESS = "ADD_ADDRESS"
export const EDIT_ADDRESS = "EDIT_ADDRESS"
export const DELETE_ADDRESS = "DELETE_ADDRESS"
